### ISSUE TITLE
Keepass http plugin incompatibly with versions 2.30, 2.31 and 2.32 of keepass 

### ISSUE THREAD

**Issue by mdesilvey** [pfn/keepasshttp#275]
Downloaded the latest of keepass initially 2.32 and installed keepass http via choco on Windows 8.1, getting the attached exception on startup of keepass with the latest version of keepass http installed.

![keepass_html_startup_exception](https://cloud.githubusercontent.com/assets/9343206/15100326/e1dd2eda-152b-11e6-817b-cd8eddb587cd.png)

**Comment by kkomelin** [comment]
The same on Ubuntu

**Comment by MattMattV** [comment]
I have same type of issue with Ubuntu 15.04 and KeePass 2.33 with that error :

![GitHub Logo](http://i.imgur.com/BPsrJgX.png)

**Comment by luzat** [comment]
Not sure when exactly, but recently started to appear here (Debian, Mono, KeePass 2.33 now, plugin cache cleared) too. It probably happened with 1.84.0 already, but persists after upgrading to 1.84.1.

**Comment by LEDfan** [comment]
I had the same issue on openSUSE 13.2 with Keepass 2.33. I had the same problem as in https://github.com/pfn/keepasshttp/issues/275. Just killed all keepass instances and it worked again.

**Comment by jjlauer** [comment]
Same issue.  I tried downloading versions all the way back to mid-last year and same error keeps popping up.  I'm on Ubuntu 14.04 (Linux Mint 17.3).

**Comment by swiftfall** [comment]
I was just having the same problems in Ubuntu I saw the "Tips to run KeePassHttp on lastest KeePass 2.31".
Had to run `sudo apt-get install libmono-system-xml-linq4.0-cil libmono-system-data-datasetextensions4.0-cil libmono-system-runtime-serialization4.0-cil mono-mcs`

**Comment by jjlauer** [comment]
@swiftfall That fixed my issue.

**Comment by Akuukis** [comment]
@swiftfall It solved my issue on Debian8, Mono 3.2.8 and KeePass 2.28

**Comment by arieljlira** [comment]
Same problem in Ubuntu 16.04 and Keepass 2.32. 
Solved with @swiftfall suggested packages. Thanks!

**Comment by jheld** [comment]
I suggest we close this issue; the work-around (apt-get installation) is present in the README.

**Comment by pascalopitz** [comment]
Doesn't work for me on Ubuntu 16.04, despite running  `sudo apt-get install libmono-system-xml-linq4.0-cil libmono-system-data-datasetextensions4.0-cil libmono-system-runtime-serialization4.0-cil mono-mcs`

Still getting this:
![image](https://cloud.githubusercontent.com/assets/271740/16508389/9dd05eea-3f71-11e6-91f3-74744e140586.png)

**Comment by jhult** [comment]
Installing the above packages did not resolve the issue for me. But, installing _mono-complete_ did.

**Comment by rakshazi** [comment]
Ubuntu 16.04 amd64
KeePass2 v2.32 (Dev)
`mono-complete` package installed, KeePassHttp.plgx downloaded in /usr/lib/keepass2/ and changed rights (for plgx) to 644.

Restarted KeePass2, but don't see plugin settings menu item in `Tools` menu.

Explain, please, how can I fix it?

**Comment by jhult** [comment]
@rakshazi - have you tried clearing the Plugin cache? Within KeePass, go to Tools > Plugins > Clear.

**Comment by rakshazi** [comment]
@jhult sorry, but this didn't help, too.

**Comment by Caffenicotiak** [comment]
I have exactly the same problem here on a Windows 10 x64 machine with KeyPass 2.34 and KeyPassHttp 1.8.4.1. 
Tried deleting the cache files, reinstalling Keypass and so on, nothing worked. 
And I do NOT find the problem described in the README (there, only issues with multiple KeyPassHttp.plgx files are addressed, or did I miss something?)

**Comment by hknet** [comment]
I have to second the report by Caffenicotiak, chromeIPass always tells me it's not connected and I have to reconnect it, while KeePassHTTP has the key for ipass, removed, reinstalled, removed, ... nothing seems to solve this issue, yet it first came up with a new Win10 x64 install on this machine.

**Comment by isnogud** [comment]
I had the exact same problem with Windows 10 x64. I did some research with the exception message and found another thread that had a problem with "SetFileCompletionNotificationModes". In this case the culprit was a buggy uninstalling of a Lavasoft software. So it left the LavasoftTcpService64.dll in the System32 directory. To remove it I followed these instructions (http://www.lavasoftsupport.com/index.php?/topic/34311-cannot-completely-remove-webcompanion/) and after a reboot it works like a charm again!

**Comment by hknet** [comment]
no lavasoft here :)

**Comment by sebastianrothe** [comment]
Okay, Im on Ubuntu and I had one process idling, while KeePass was closed. So reboot your machine or kill this process.
`ps aux | grep keepass
sudo kill -i9 <id>
`


I will also suggest this on this Issue https://github.com/pfn/keepasshttp/issues/287

**Comment by therompalace** [comment]
@Caffenicotiak Don't know why it worked, but that resolved the issue on my Win 8 x64 machine. Thanks!

**Comment by mdesilvey** [comment]
Thanks @Caffenicotiak, simply running:  `netsh winsock reset` worked for me.  I didn't have to remove Lavasoft dlls since they didn't exist on my machine.

For users different then that of Windows, I can't test the fix since I originally posted this issue for Windows.  I am willing to have this issue closed out.
